### ISSUE TITLE
debugging setting in DrRacket causes link errors at runtime

### ISSUE THREAD

**Issue by dyoo** [dyoo/whalesong#15]
If debugging is on in DrRacket, Whalesong programs produce an error at runtime that's bizzare:

link: module mismatch, probably from old bytecode whose dependencies have changed: variable not provided (directly or indirectly) from module:  ...

**Comment by soegaard** [comment]
Note: The error also disappears if one disables DrRacket's use of the "compiled" folders.

**Comment by dyoo** [comment]
Should be resolved in af503884502394a9bb356bf512030eb523f26685 now.
