### ISSUE TITLE
raco setup issues: file permissions failures

### ISSUE THREAD

**Issue by dougo** [dyoo/whalesong#17]
I got two error messages when doing raco setup (following the instructions at http://hashcollision.org/whalesong/ ).  I don't know what's up with the first one.  The second one is a permission error, because I didn't run it as root, but the instructions seem to imply that the launcher will be created in the current directory, rather than /usr/bin.

$ raco setup -P dyoo whalesong.plt 1 0
raco setup: version: 5.1.3 [3m]
raco setup: variants: 3m
raco setup: main collects: /usr/share/racket/collects
raco setup: collects paths: 
raco setup:   /home/dougo/.racket/5.1.3/collects
raco setup:   /usr/share/racket/collects
raco setup: --- pre-installing collections ---
raco setup: --- compiling collections ---
raco setup: making: racket
raco setup: --- parallel build using 2 processes ---
raco setup: making: /home/dougo/whalesong (Whalesong)
raco setup:  in /home/dougo/whalesong/
user break
user break
raco setup:  in /home/dougo/whalesong/lang/
raco setup:  in /home/dougo/whalesong/image/
raco setup:  in /home/dougo/whalesong/lang/private/
raco setup:  in /home/dougo/whalesong/lang/unsafe/
raco setup:  in /home/dougo/whalesong/lang/js/
raco setup:  in /home/dougo/whalesong/image/private/
raco setup:  in /home/dougo/whalesong/resource/
raco setup:  in /home/dougo/whalesong/compiler/
raco setup:  in /home/dougo/whalesong/js/
raco setup:  in /home/dougo/whalesong/world/
raco setup:  in /home/dougo/whalesong/private/
raco setup:  in /home/dougo/whalesong/make/
raco setup:  in /home/dougo/whalesong/parser/
raco setup:  in /home/dougo/whalesong/version-case/
raco setup:  in /home/dougo/whalesong/js-assembler/
require: unknown module: 'program
raco setup: error: during Building docs for /home/dougo/.racket/planet/300/5.1.3/cache/dyoo/closure-compile.plt/1/2/manual.scrbl
raco setup:   require: unknown module: 'program
raco setup:  in /home/dougo/whalesong/web-world/
raco setup:  in /home/dougo/whalesong/scribblings/
raco setup: making: /home/dougo/whalesong/base
raco setup: making: /home/dougo/whalesong/base/lang
raco setup:  in /home/dougo/whalesong/base/lang/
raco setup: making: /home/dougo/whalesong/bf
raco setup:  in /home/dougo/whalesong/bf/
raco setup:  in /home/dougo/whalesong/lang/
raco setup:  in /home/dougo/whalesong/lang/private/
raco setup:  in /home/dougo/whalesong/lang/check-expect/
raco setup: making: /home/dougo/whalesong/bf/lang
raco setup:  in /home/dougo/whalesong/bf/lang/
raco setup: making: /home/dougo/whalesong/compiler
raco setup:  in /home/dougo/whalesong/compiler/
raco setup: making: /home/dougo/whalesong/image
raco setup: making: /home/dougo/whalesong/image/private
raco setup: making: /home/dougo/whalesong/images
raco setup: making: /home/dougo/whalesong/js
raco setup: making: /home/dougo/whalesong/js-assembler
raco setup:  in /home/dougo/whalesong/js-assembler/
raco setup: making: /home/dougo/whalesong/js-assembler/runtime-src
raco setup: making: /home/dougo/whalesong/korean
raco setup: making: /home/dougo/whalesong/korean/lang
raco setup:  in /home/dougo/whalesong/korean/lang/
raco setup: making: /home/dougo/whalesong/lang
raco setup:  in /home/dougo/whalesong/lang/
raco setup: making: /home/dougo/whalesong/lang/base
raco setup:  in /home/dougo/whalesong/lang/base/
raco setup: making: /home/dougo/whalesong/lang/check-expect
raco setup: making: /home/dougo/whalesong/lang/js
raco setup: making: /home/dougo/whalesong/lang/private
raco setup: making: /home/dougo/whalesong/lang/unsafe
raco setup: making: /home/dougo/whalesong/make
raco setup: making: /home/dougo/whalesong/notes
raco setup: making: /home/dougo/whalesong/parser
raco setup:  in /home/dougo/whalesong/parser/
raco setup: making: /home/dougo/whalesong/private
raco setup: making: /home/dougo/whalesong/resource
raco setup: making: /home/dougo/whalesong/scribblings
raco setup: making: /home/dougo/whalesong/tool
raco setup:  in /home/dougo/whalesong/tool/
raco setup: making: /home/dougo/whalesong/version-case
raco setup: making: /home/dougo/whalesong/web-world
raco setup: making: /home/dougo/whalesong/world
raco setup: --- updating info-domain tables ---
raco setup: updating: /home/dougo/.racket/planet/300/5.1.3/cache.rktd
raco setup: --- creating launchers ---
raco setup: launcher: <console-bin>/whalesong
copy-file: cannot open destination file; cannot copy: /usr/share/racket/collects/launcher/sh to: /usr/bin/whalesong (Permission denied; errno=13)
raco setup: --- building documentation ---
raco setup: skipping: <planet>/dyoo/closure-compile.plt/1/2/manual.scrbl
raco setup: skipping: handin-server/scribblings/handin-server.scrbl
raco setup: running: /home/dougo/whalesong/scribblings/manual.scrbl
raco setup: rendering: /home/dougo/whalesong/scribblings/manual.scrbl
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco setup: 
raco setup: error: during Launcher Setup for /home/dougo/whalesong (Whalesong)
raco setup:   copy-file: cannot open destination file; cannot copy: /usr/share/racket/collects/launcher/sh to: /usr/bin/whalesong (Permission denied; errno=13)

**Comment by dyoo** [comment]
> I got two error messages when doing raco setup (following the instructions at http://hashcollision.org/whalesong/ ).  I don't know what's up with the first one.

Ah, ok.  The first one is a bug in Racket, and should be fixed in the
next release.  See the thread in:

```
http://lists.racket-lang.org/dev/archive/2011-August/007476.html
```

for more details.

The second is a permission error, yes.  I need to ask how to make
launchers that are user-specific, rather than systemwide.  I already
do a personalized launcher in make-launcher.rkt, so maybe I should
just turn off the creation of the launcher made at PLaneT-package
install time.

**Comment by dyoo** [comment]
Changed the info.rkt not to build the launcher anymore, so it should not raise the file permission error.  The documentation in the scribble doc has been revised with a step on how to make the whalesong launcher manually.  I'll close this issue when I push the doc update up.

**Comment by dyoo** [comment]
Closing issue; documentation updated.
