### ISSUE TITLE
typesetting error for "--" in manual

### ISSUE THREAD

**Issue by dougo** [dyoo/whalesong#18]
The manual says "–compress-javascript" when it should say "--compress-javascript" (i.e. the two hyphens turn into a Unicode dash).  Same for "--verbose".  This is pretty minor, but I was temporarily confused about whether it meant one hyphen or two...

**Comment by dyoo** [comment]
On Mon, Sep 5, 2011 at 8:35 PM, dougo
reply@reply.github.com
wrote:

> The manual says "–compress-javascript" when it should say "--compress-javascript" (i.e. the two hyphens turn into a Unicode dash).  Same for "--verbose".  This is pretty minor, but I was temporarily confused about whether it meant one hyphen or two...

I see.  I probably will need to use the non-breaking hyphen character
described in http://docs.racket-lang.org/scribble/base.html#(def._((lib._scribble/base..rkt)._-~7e-))

Thanks; I'll patch the docs shortly.

**Comment by dougo** [comment]
I think you can use verbatim?

On Mon, Sep 5, 2011 at 9:26 PM, dyoo
reply@reply.github.com
wrote:

**Comment by dyoo** [comment]
On Mon, Sep 5, 2011 at 9:30 PM, dougo
reply@reply.github.com
wrote:

> I think you can use verbatim?

But that would be too easy, right?  :)

Doh!  Thanks.  Verbatim it is then.

**Comment by dyoo** [comment]
Will be fixed with https://github.com/dyoo/whalesong/commit/f0ccc5c5123751d0ea3d77433f18f2cc006dc7a0.  Closing issue.
