### ISSUE TITLE
list->string and substring not exposed

### ISSUE THREAD

**Issue by soegaard** [dyoo/whalesong#3]
I am missing the primitives list->string and substring among the exposed functions for immutable strings.
Given these constructors, I can easily write temporary implementations of most string functions
in my own code.

**Comment by dyoo** [comment]
> I am missing the primitives list->string and substring among the exposed functions for immutable strings.
> Given these constructors, I can easily write temporary implementations of most string functions
> in my own code.

Ok, added list->string and substring into the repository.  I've been a
bit behind with the important standard library functions.  Let me know
which ones you'll need, and I'll prioritize toward those.
