### ISSUE TITLE
last-commit-name.rkt missing?

### ISSUE THREAD

**Issue by soegaard** [dyoo/whalesong#4]
Hi,

JFYI the following error appears during "raco setup" of whalesong.

default-load-handler: cannot open input file: "/Users/soegaard/Dropbox/GitHub/stxmat-exercises/whalesong/current/last-commit-name.rkt" (No such file or directory; errno=2)

/Jens Axel

**Comment by dyoo** [comment]
> JFYI the following error appears during "raco setup" of whalesong.
> 
> default-load-handler: cannot open input file: "/Users/soegaard/Dropbox/GitHub/stxmat-exercises/whalesong/current/last-commit-name.rkt" (No such file or directory; errno=2)

Ok, I will need to fix my build process so that I don't need that
file... in the meantime, run 'make-last-commit-name.rkt' in the
whalesong directory and try again.

**Comment by soegaard** [comment]
No hurry. The error doesn't break anything (as far as I can tell).

/Jens Axel

2011/8/18 dyoo <
reply@reply.github.com>

> > JFYI the following error appears during "raco setup" of whalesong.
> > 
> > default-load-handler: cannot open input file:
> > "/Users/soegaard/Dropbox/GitHub/stxmat-exercises/whalesong/current/last-commit-name.rkt"
> > (No such file or directory; errno=2)
> 
> Ok, I will need to fix my build process so that I don't need that
> file... in the meantime, run 'make-last-commit-name.rkt' in the
> whalesong directory and try again.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dyoo/whalesong/issues/4#issuecomment-1842606

## 

## 

Jens Axel Søgaard

**Comment by dyoo** [comment]
On Thu, Aug 18, 2011 at 4:43 PM, soegaard
reply@reply.github.com
wrote:

> No hurry. The error doesn't break anything (as far as I can tell).

Yeah, it should only be used in the generation of the Scribble
documentation --- I use it so the docs have the git commit id at the
very top.

**Comment by dyoo** [comment]
Closing issue; file removed.  The scribble doc will itself conditionally look to see if it can derive a git commit name, and if it can't, it should go on without error.
