### ISSUE TITLE
IE compatibility issues

### ISSUE THREAD

**Issue by dyoo** [dyoo/whalesong#46]
On IE, canvas-related programs are not running correctly.  See SK's words.rkt program, for example.  We need the silly IE compatibility shims, I think.

**Comment by schanzer** [comment]
Yeah, this doesn't surprise me, since IE doesn't actually have a canvas element until v9 (or is it 8? either way...)

If the Chrome Frame method works, it will eliminate the need for those shims altogether.

**Comment by dyoo** [comment]
Compatibility shims added to Whalesong.  Closing issue.
