### ISSUE TITLE
view-bind-*

### ISSUE THREAD

**Issue by soegaard** [dyoo/whalesong#80]
The names of the event bound with the view-bind-\* functions use jquery names and not JavaScript names.
In particulary the event named onkeyup in JavaScript must be named keyup.
I suggest adding a note about this in the documentation.

**Comment by dyoo** [comment]
On Sun, Feb 12, 2012 at 3:08 PM, Jens Axel Søgaard
reply@reply.github.com
wrote:

> The names of the event bound with the view-bind-\* functions use jquery names and not JavaScript names.
> In particulary the event named onkeyup in JavaScript must be named keyup.
> I suggest adding a note about this in the documentation.

I've added a small sentence or two to the development docs in
1a6e08213bc61de6d7e7f0cdeb1ce0017c1c606d.  Is it sufficient?

**Comment by soegaard** [comment]
Yes, that fine.

Thanks,
Jens Axel

2012/2/13 Danny Yoo <
reply@reply.github.com

> On Sun, Feb 12, 2012 at 3:08 PM, Jens Axel Søgaard
> reply@reply.github.com
> wrote:
> 
> > The names of the event bound with the view-bind-\* functions use jquery
> > names and not JavaScript names.
> > In particulary the event named onkeyup in JavaScript must be named keyup.
> > I suggest adding a note about this in the documentation.
> 
> I've added a small sentence or two to the development docs in
> 1a6e08213bc61de6d7e7f0cdeb1ce0017c1c606d.  Is it sufficient?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dyoo/whalesong/issues/80#issuecomment-3947101

## 

## 

Jens Axel Søgaard
