### ISSUE TITLE
make test-all fails

### ISSUE THREAD

**Issue by soegaard** [dyoo/whalesong#86]
It seems as though lam-entry-gensym.rkt has disappeared in recent versions?

mba-2:whalesong soegaard$ make test-all

racket tests/test-all.rkt
default-load-handler: cannot open input file: "/Users/soegaard/Dropbox/GitHub/whalesong/parser/lam-entry-gensym.rkt" (No such file or directory; errno=2)

 === context ===
standard-module-name-resolver
standard-module-name-resolver
standard-module-name-resolver

make: **\* [test-all] Error 1

**Comment by dyoo** [comment]
> mba-2:whalesong soegaard$ make test-all
> 
> racket tests/test-all.rkt
> default-load-handler: cannot open input file: "/Users/soegaard/Dropbox/GitHub/whalesong/parser/lam-entry-gensym.rkt" (No such file or directory; errno=2)

Ah!  I have to fix the test harness; the tests I'm running regularly
are now of the form:

```
$ make test-more
```

which will fire up the web browser and run a bunch of tests there.

test-all used to test the simulator and a bunch of other code that I'm
not using anymore; I should have pruned that make target away.

**Comment by soegaard** [comment]
Ah, that explains it.

**Comment by dyoo** [comment]
a19c7c180875b6dd8857e5ff99327c96158ca597 will eliminate the broken make targets

**Comment by dyoo** [comment]
On Mon, Feb 27, 2012 at 12:37 PM, Jens Axel Søgaard
reply@reply.github.com
wrote:

> Ah, that explains it.

Ok, I've pushed a change to the Makefile so that 'test-all' is an
alias to 'test-more'; I'll revive more of the tests soon.
