### ISSUE TITLE
make test-compiler

### ISSUE THREAD

**Issue by soegaard** [dyoo/whalesong#87]
It seems the simulator is missing?

mba-2:whalesong soegaard$ make test-compiler

racket tests/test-compiler.rkt
default-load-handler: cannot open input file: "/Users/soegaard/Dropbox/GitHub/whalesong/simulator/simulator.rkt" (No such file or directory; errno=2)

 === context ===
standard-module-name-resolver
standard-module-name-resolver

make: **\* [test-compiler] Error 1

**Comment by dyoo** [comment]
On Mon, Feb 27, 2012 at 12:37 PM, Jens Axel Søgaard
reply@reply.github.com
wrote:

> It seems the simulator is missing?

I ripped out the simulator a while back.  I have to revise all of the
tests that depended on the simulator to work on the real browser.
